name: PR
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  issue_comment:
    types:
      - created

jobs:
  sync:
    runs-on: ubuntu-latest

    # Avoid running on issue comments
    if: ${{ github.event.pull_request || github.event.issue.pull_request }}

    steps:
      - uses: kozmoai/actions/pr-sync@v0.6.2
        with:
          github-token: ${{ secrets.API_GITHUB_TOKEN  }}
          app-id: ${{ secrets.GLINT_GOALIE_APPLICATION_ID }}
          private-key: ${{ secrets.GLINT_GOALIE_PRIVATE_KEY }}
          installation-id: ${{ secrets.GLINT_GOALIE_INSTALLATION_ID }}
          project-id: PVT_kwDOBFKqdc02LQ
          auto-assign: false
          excluded-users: freben
          owning-teams: '@kozmoai/techdocs'
